sonar.projectKey=momode12_projet_qualimetrie
sonar.organization=momode12
sonar.sources=src,routes
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**